CREATE TABLE PRODUCT (
   id INTEGER PRIMARY KEY,
   productName VARCHAR(255) NOT NULL,
   status VARCHAR(255) NOT NULL
);

INSERT INTO PRODUCT VALUES (1, 'Product1', 'INACTIVE'), (2, 'Product2', 'ACTIVE'), (3, 'Product3', 'IN_DESIGN');